from Question import *
a = Question()
a.set_sort_key("5")
a.set_partition_key("questions")

a.set_question_id("5")
a.set_title("What are you here for?")
a.set_subtitle("Select as many as you want")
a.set_subtitle_2("")
a.set_warning("Wrongly stating intent (or any other info hereafter) could lead to loss of Club Membership & Fees.")
a.set_warning_type("")
a.set_question_type("Intent")
a.set_option_type("list_cell_snippet")
a.set_selection_type("multi_selection")
a.set_progress("0.35")
a.set_conditions("")
a.set_next_button_text("I am 100% sure!")

options = []
o = Options()
o.set_option_id("1")
o.set_option_image_url("Infinity")
o.set_option_text("Marry")
o.set_option_subtext("Ready to get married, with family involved, from the first one-on-one meeting")
options.append(o)
o = Options()
o.set_option_id("2")
o.set_option_image_url("Staircase")
o.set_option_text("Date to Marry")
o.set_option_subtext("Want to date with the serious intent to get married in max 2yrs")
options.append(o)
o = Options()
o.set_option_id("3")
o.set_option_image_url("Heart")
o.set_option_text("Exclusively Date")
o.set_option_subtext("Not sure if/when I want to get married, but want an exclusive relationship with emotional bonding")
options.append(o)
o = Options()
o.set_option_id("4")
o.set_option_image_url("Lightning")
o.set_option_text("Casually Date")
o.set_option_subtext("Seek a partner without commitment, exclusivity or emotional attachment")
options.append(o)

ops = options.__str__()
a.set_options(ops)
rep = a.__str__()