from Question import *
a = Question()
a.set_sort_key("7")
a.set_partition_key("questions")

a.set_question_id("7")
a.set_title("What's your marital status?")
a.set_subtitle("")
a.set_subtitle_2("")
a.set_warning("")
a.set_warning_type("")
a.set_question_type("Marital_Status")
a.set_option_type("list_cell_snippet")
a.set_selection_type("single_selection")
a.set_progress("0.45")
a.set_conditions("")
a.set_next_button_text("Next")

options = []
o = Options()
o.set_option_id("1")
o.set_option_image_url("")
o.set_option_text("Never Married")
options.append(o)
o = Options()
o.set_option_id("2")
o.set_option_image_url("")
o.set_option_text("Windowed")
options.append(o)
o = Options()
o.set_option_id("3")
o.set_option_image_url("")
o.set_option_text("Divorced")
options.append(o)
o = Options()
o.set_option_id("4")
o.set_option_image_url("")
o.set_option_text("Separated/divorce in progress")
options.append(o)

ops = options.__str__()
a.set_options(ops)
rep = a.__str__()