from Question import *
a = Question()
a.set_sort_key("8")
a.set_partition_key("questions")

a.set_question_id("8")
a.set_title("Do you have children?")
a.set_subtitle("")
a.set_subtitle_2("")
a.set_warning("")
a.set_warning_type("")
a.set_question_type("Children")
a.set_option_type("list_cell_snippet")
a.set_selection_type("single_selection")
a.set_progress("0.5")
a.set_conditions("")
a.set_next_button_text("Next")

options = []
o = Options()
o.set_option_id("1")
o.set_option_image_url("Tick")
o.set_option_text("Yes, and want more")
options.append(o)
o = Options()
o.set_option_id("2")
o.set_option_image_url("Tick")
o.set_option_text("Yes, and unsure if I want more")
options.append(o)
o = Options()
o.set_option_id("3")
o.set_option_image_url("Tick")
o.set_option_text("Yes, and I don't want more")
options.append(o)
o = Options()
o.set_option_id("4")
o.set_option_image_url("Cross")
o.set_option_text("No, but I want someday")
options.append(o)
o = Options()
o.set_option_id("5")
o.set_option_image_url("Cross")
o.set_option_text("No, and not sure if I want to")
options.append(o)
o = Options()
o.set_option_id("6")
o.set_option_image_url("Cross")
o.set_option_text("No, and I don't want to ever")
options.append(o)

ops = options.__str__()
a.set_options(ops)
rep = a.__str__()