from Question import *
a = Question()
a.set_sort_key("11")
a.set_partition_key("questions")

a.set_question_id("11")
at = TextItem()
at.set_text("Do you indulge in these?")
a.set_title(at)
a.set_subtitle("")
a.set_subtitle_2("")
a.set_warning("")
a.set_warning_type("")
a.set_question_type("Indulgement")
a.set_option_type("list_cell_snippet")
a.set_selection_type("single_selection")
a.set_progress("0.5")
a.set_conditions("")
a.set_next_button_text("Next")

options = []
o = Options()
o.set_option_id("1")
o.set_option_text("Smoke")
o.set_option_text_left_icon("ea69")
ot = TextItem()
ot.set_text("Smoke")
ot.set_left_icon("ea69")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("2")
o.set_option_text("Drink")
o.set_option_text_left_icon("edd9")
ot = TextItem()
ot.set_text("Drink")
ot.set_left_icon("eaedd969")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("3")
o.set_option_image_url("Pill")
o.set_option_text("Marijuana")
o.set_option_text_left_icon("ec77")
ot = TextItem()
ot.set_text("Marijuana")
ot.set_left_icon("ec77")
o.set_option_title(ot)
#//////
o.set_option_subtext("Not Shown on your profile")
o.set_option_subtext_left_icon("ead3")
ot = TextItem()
ot.set_text("Not Shown on your profile")
ot.set_left_icon("ead3")
o.set_option_subtitle(ot)
#/////
options.append(o)

ops = options.__str__()
a.set_options(ops)
rep = a.__str__()