from Question import *
a = Question()
a.set_sort_key("11")
a.set_partition_key("questions")

a.set_question_id("11")
at = TextItem()
at.set_text("Do you consume marijuana?")
a.set_title(at)
at = TextItem()
at.set_text("Not shown on your profile")
at.set_left_icon("ead3")
a.set_subtitle(at)
a.set_subtitle_2("")
a.set_alert("")
a.set_alert_type("")
a.set_question_type("Marijuana")
a.set_layout("v_list")
a.set_selection_type("1")
a.set_progress(f"{int(a.question_id)/TOTAL_QUESTIONS :.2f}")
a.set_conditions("")
a.set_next_button_text("Next")
a.set_skip_button_text("Skip for now")



options = []
o = Option()
o.set_option_id("1")
ot = TextItem()
ot.set_text("Never")
o.set_option_title(ot)
o.set_option_type("option_card")
options.append(o)
o = Option()
o.set_option_id("2")
ot = TextItem()
ot.set_text("Sometimes")
o.set_option_title(ot)
o.set_option_type("option_card")
options.append(o)
o = Option()
o.set_option_id("3")
ot = TextItem()
ot.set_text("Regularly")
o.set_option_title(ot)
o.set_option_type("option_card")
options.append(o)

ops = options.__str__()
a.set_options(ops)

rep = a.__str__()