from Question import *
a = Question()
a.set_sort_key("13")
a.set_partition_key("questions")

a.set_question_id("13")
at = TextItem()
at.set_text("Tell me about your work")
a.set_title(at)
a.set_subtitle("")
a.set_subtitle_2("")
a.set_alert("")
a.set_alert_type("")
a.set_question_type("Employment")
a.set_layout("v_list")
a.set_selection_type("single_selection")
a.set_progress(f"{int(a.question_id)/TOTAL_QUESTIONS :.2f}")
a.set_conditions("")
a.set_next_button_text("Next")
a.set_skip_button_text("I have never worked")

options = []
o = Option()
o.set_option_id("1")
ot = TextItem()
ot.set_text("Nature of work")
ot.set_right_icon("ebdd")
o.set_option_title(ot)
o.set_option_type("option_card")
bs = BottomSheet()
bs.set_selection_type("1")
ot = TextItem()
ot.set_text("Nature of work")
bs.set_title(ot)
bs.set_layout("v_list")
bsops = []
bso = Option()
bso.set_option_id("1")
bsot = TextItem()
bsot.set_text("Malik")
bso.set_option_title(bsot)
bso.set_option_type("list_item_large")
bsops.append(bso)
bso = Option()
bso.set_option_id("2")
bsot = TextItem()
bsot.set_text("Berozgar")
bso.set_option_title(bsot)
bso.set_option_type("list_item_large")
bsops.append(bso)
bs.set_options(bsops)
o.set_bottom_sheet(bs)
options.append(o)

o = Option()
o.set_option_id("2")
ot = TextItem()
ot.set_text("Name of company")
ot.set_right_icon("ebdd")
o.set_option_title(ot)
o.set_option_type("option_card")
bs = BottomSheet()
bs.set_selection_type("1")
ot = TextItem()
ot.set_text("Name of company")
bs.set_title(ot)
bs.set_layout("bottom_sheet_search_field")
bsops = []
bso = Option()
bso.set_option_id("1")
bsotf = TextField()
bsotf.set_left_icon("ebdd")
bsotft = TextItem()
bsotft.set_text("Start Typing")
bsotf.set_placeholder(bsotft)
bso.set_option_text_field(bsotf)
bsops.append(bso)
bs.set_options(bsops)
o.set_bottom_sheet(bs)
options.append(o)

o = Option()
o.set_option_id("3")
ot = TextItem()
ot.set_text("Your role")
ot.set_right_icon("ebdd")
o.set_option_title(ot)
o.set_option_type("option_card")
bs = BottomSheet()
bs.set_selection_type("1")
ot = TextItem()
ot.set_text("Your role")
bs.set_title(ot)
bs.set_layout("bottom_sheet_search_field")
bsops = []
bso = Option()
bso.set_option_id("1")
bsotf = TextField()
bsotf.set_left_icon("ebdd")
bsotft = TextItem()
bsotft.set_text("Start Typing")
bsotf.set_placeholder(bsotft)
bso.set_option_text_field(bsotf)
bsops.append(bso)
bs.set_options(bsops)
o.set_bottom_sheet(bs)
options.append(o)
# options = []
# o = Option()
# o.set_option_id("1")
# ot = TextItem()
# ot.set_text("Family Business")
# o.set_option_title(ot)
# options.append(o)
# o = Option()
# o.set_option_id("2")
# ot = TextItem()
# ot.set_text("Business Founder / Own Practice")
# o.set_option_title(ot)
# options.append(o)
# o = Option()
# o.set_option_id("3")
# ot = TextItem()
# ot.set_text("Private Sector Employee")
# o.set_option_title(ot)
# options.append(o)
# o = Option()
# o.set_option_id("4")
# ot = TextItem()
# ot.set_text("Govt / Public Sector Employee")
# o.set_option_title(ot)
# options.append(o)
# o = Option()
# o.set_option_id("5")
# ot = TextItem()
# ot.set_text("Sabbatical")
# o.set_option_title(ot)
# options.append(o)
# o = Option()
# o.set_option_id("6")
# ot = TextItem()
# ot.set_text("Freelance")
# o.set_option_title(ot)
# options.append(o)
# o = Option()
# o.set_option_id("7")
# ot = TextItem()
# ot.set_text("Unemployed")
# o.set_option_title(ot)
# options.append(o)
# o = Option()
# o.set_option_id("8")
# ot = TextItem()
# ot.set_text("Student")
# o.set_option_title(ot)
# options.append(o)
# o = Option()
# o.set_option_id("9")
# ot = TextItem()
# ot.set_text("Retired")
# o.set_option_title(ot)
# options.append(o)

ops = options.__str__()
a.set_options(ops)
rep = a.__str__()