from Question import *
a = Question()
a.set_sort_key("14")
a.set_partition_key("questions")

a.set_question_id(a.sort_key)
at = TextItem()
at.set_text("Would you want to take your family along for the first Meet?")
a.set_title(at)
at = TextItem()
# at.set_text("Not shown on your profile")
# at.set_left_icon("ead3")
a.set_subtitle("")
a.set_subtitle_2("")
a.set_alert("")
a.set_alert_type("")
a.set_question_type("question_take_family_first_meet")
a.set_layout("v_list")
a.set_selection_type("1")
a.set_progress(f"{int(a.question_id)/TOTAL_QUESTIONS :.2f}")
a.set_conditions("")
a.set_next_button_text("Next")
a.set_next_button_id(f"qs_{a.question_id}_next")


options = []
o = Option()
o.set_option_id("1")
ot = TextItem()
ot.set_text("I prefer to")
o.set_option_title(ot)
o.set_option_type("option_card")
options.append(o)
o = Option()
o.set_option_id("2")
ot = TextItem()
ot.set_text("I prefer not to")
o.set_option_title(ot)
o.set_option_type("option_card")
options.append(o)

conditions = []
c = Conditions()
c.set_question_id("3")
c.set_option("1")
conditions.append(c)
conditions = conditions.__str__()
a.set_conditions(conditions)

ops = options.__str__()
a.set_options(ops)

rep = a.__str__()