from Question import *
a = Question()
a.set_sort_key("16")
a.set_partition_key("questions")

a.set_question_id("16")
at = TextItem()
at.set_text("Which Profession are you in?")
a.set_title(at)
a.set_subtitle("")
a.set_subtitle_2("")
a.set_warning("")
a.set_warning_type("")
a.set_question_type("Profession")
a.set_option_type("list_cell_snippet")
a.set_selection_type("single_selection")
a.set_progress("0.72")
a.set_conditions("")
a.set_next_button_text("Next")

options = []
o = Options()
o.set_option_id("1")
o.set_option_text("Business Management/Finance")
ot = TextItem()
ot.set_text("Business Management/Finance")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("2")
o.set_option_text("Salaried")
ot = TextItem()
ot.set_text("Salaried")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("3")
o.set_option_text("Freelance")
ot = TextItem()
ot.set_text("Freelance")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("4")
o.set_option_text("Unemployed")
ot = TextItem()
ot.set_text("Unemployed")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("5")
o.set_option_text("Retired")
ot = TextItem()
ot.set_text("Retired")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("6")
o.set_option_text("Student")
ot = TextItem()
ot.set_text("Student")
o.set_option_title(ot)
options.append(o)


ops = options.__str__()
a.set_options(ops)
rep = a.__str__()