from Question import *
a = Question()
a.set_sort_key("17")
a.set_partition_key("questions")
a.set_question_id(a.sort_key)
at = TextItem()
at.set_text("Tell me about your physique")
a.set_title(at)
a.set_subtitle("")
a.set_subtitle_2("")
at = TextItem()
at.set_text("Numerical weight not shown on profile")
at.set_left_icon("ead3")
a.set_subtitle_3(at)
a.set_alert("This will help me match you with a partner who respects your body type and avoids any first meeting surprises or awkwardness")
a.set_alert_type("info")
a.set_question_type("question_physique")
a.set_layout("height_and_weight")
a.set_selection_type("1")
a.set_progress(f"{int(a.question_id)/TOTAL_QUESTIONS :.2f}")
a.set_conditions("")
a.set_next_button_text("Next")
a.set_next_button_id(f"qs_{a.question_id}_next")

options = []
o = Option()
o.set_option_id("1")
ot = TextItem()
ot.set_text("Add height")
ot.set_left_icon("ecbb")
o.set_option_title(ot)
o.set_option_type("height")
bs = BottomSheet()
bs.set_button_2_text("Add criteria")
bs.set_button_2_left_icon("ec86")
bs.set_selection_type("1")
ot = TextItem()
ot.set_text("Add height")
bs.set_title(ot)
bs.set_screen_type("criteria_screen")
bs.set_layout("height_picker")

o.set_bottom_sheet(bs)
options.append(o)

o = Option()
o.set_option_id("2")
ot = TextItem()
ot.set_text("Add weight")
ot.set_left_icon("ec63")
o.set_option_title(ot)
o.set_option_type("weight")
bs = BottomSheet()
bs.set_button_2_text("Add criteria")
bs.set_button_2_left_icon("ec86")
bs.set_selection_type("1")
ot = TextItem()
ot.set_text("Add weight")
bs.set_title(ot)
bs.set_screen_type("criteria_screen")
bs.set_layout("v_list")
bsops = []
bso = Option()
bso.set_option_id("2.1")
bso.set_option_type("option_card")
bsops.append(bso)
bs.set_options(bsops)
o.set_bottom_sheet(bs)
options.append(o)


ops = options.__str__()
a.set_options(ops)


rep = a.__str__()