from Question import *
a = Question()
a.set_sort_key("18")
a.set_partition_key("questions")

a.set_question_id("18")
at = TextItem()
at.set_text("How much do you earn in a year?")
a.set_title(at)
at = TextItem()
at.set_text("Not shown on your profile, just between us so you can be honest")
at.set_left_icon("ead3")
a.set_subtitle(at)
a.set_subtitle_2("")
a.set_alert("")
a.set_alert_type("")
a.set_question_type("Income")
a.set_option_type("list_cell_snippet")
a.set_selection_type("single_selection")
a.set_progress(f"{int(a.question_id)/TOTAL_QUESTIONS :.2f}")
a.set_conditions("")
a.set_next_button_text("Next")

options = []
o = Options()
o.set_option_id("1")
ot = TextItem()
ot.set_text("₹ 5 Lakh or less")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("2")
ot = TextItem()
ot.set_text("₹ 5 to 10 lakhs")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("3")
ot = TextItem()
ot.set_text("₹ 10 to 20 lakhs")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("4")
ot = TextItem()
ot.set_text("₹ 20 to 35 lakhs")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("5")
ot = TextItem()
ot.set_text("₹ 35 to 50 lakhs")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("6")
ot = TextItem()
ot.set_text("₹ 50 lakhs to 1 crore")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("7")
ot = TextItem()
ot.set_text("₹ 1 crore or more")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("8")
ot = TextItem()
ot.set_text("Not applicable")
o.set_option_title(ot)
options.append(o)

ops = options.__str__()
a.set_options(ops)
rep = a.__str__()