from Question import *
a = Question()
a.set_sort_key("19")
a.set_partition_key("questions")

a.set_question_id("19")
at = TextItem()
at.set_text("Where were you born?")
a.set_title(at)
at = TextItem()
at.set_text("City, town or village")
a.set_subtitle(at)
at = TextItem()
at.set_text("State")
a.set_subtitle_2(at)
a.set_warning("")
a.set_warning_type("")
a.set_question_type("Birthplace")
a.set_option_type("list_cell_snippet")
a.set_selection_type("single_selection")
a.set_progress("0.86")
a.set_conditions("")
a.set_next_button_text("Next")

options = []
o = Options()
o.set_option_id("1")
o.set_option_text("Andhra Pradesh")
ot = TextItem()
ot.set_text("Andhra Pradesh")
o.set_option_title(ot)
options.append(o)

# Assam
o = Options()
o.set_option_id("2")
o.set_option_text("Assam")
ot = TextItem()
ot.set_text("Assam")
o.set_option_title(ot)
options.append(o)

ops = options.__str__()
a.set_options(ops)
rep = a.__str__()