from Question import *
a = Question()
a.set_sort_key("19")
a.set_partition_key("questions")

a.set_question_id("19")
at = TextItem()
at.set_text("Do you have any disability or serious illness?")
a.set_title(at)
a.set_subtitle("")
a.set_subtitle_2("")
a.set_alert("Certain aspects of our lives need extra understanding and care. Do any health conditions or disabilities affect your daily routine, and which you'd like to share upfront? This would help me find you a partner who's not just supportive, but appreciates the whole you")
a.set_alert_type("info")
a.set_question_type("Chronic_Illness")
a.set_option_type("card_v_list")
a.set_selection_type("single_selection")
a.set_progress(f"{int(a.question_id)/TOTAL_QUESTIONS :.2f}")
a.set_conditions("")
a.set_next_button_text("Next")

options = []
o = Options()
o.set_option_id("1")
ot = TextItem()
ot.set_text("No")
ot.set_left_icon("eddb")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("2")
ot = TextItem()
ot.set_text("Yes")
ot.set_left_icon("ea30")
o.set_option_title(ot)
of = TextField()
of.set_isMultiLine(True)
oft = TextItem()
oft.set_text("Please share a bit more...")
of.set_placeholder(oft)
o.set_option_text_field(of)
options.append(o)


ops = options.__str__()
a.set_options(ops)
rep = a.__str__()