from Question import *
a = Question()
a.set_sort_key("2")
a.set_partition_key("questions")

a.set_question_id("2")
at = TextItem()
at.set_text("Who are you interested in meeting?")
a.set_title(at)
at = TextItem()
at.set_text("Select as many as you want")
a.set_subtitle(at)
a.set_subtitle_2("")
a.set_alert("")
a.set_alert_type("")
a.set_question_type("Gender_Preference")
a.set_layout("grid")
a.set_selection_type("20")
a.set_progress(f"{int(a.question_id)/TOTAL_QUESTIONS :.2f}")
a.set_conditions("")
a.set_next_button_text("Next")

options = []
o = Option()
o.set_option_id("1")
o.set_option_image_url("Man")
ot = TextItem()
ot.set_text("Man")
o.set_option_title(ot)
o.set_option_type("image_card")
o.set_option_shape("square")
options.append(o)
o = Option()
o.set_option_id("2")
o.set_option_image_url("Woman")
ot = TextItem()
ot.set_text("Woman")
o.set_option_title(ot)
o.set_option_type("image_card")
o.set_option_shape("square")
options.append(o)
o = Option()
o.set_option_id("3")
o.set_option_image_url("OtherGender")
ot = TextItem()
ot.set_text("Other")
o.set_option_title(ot)
o.set_option_type("image_card")
o.set_option_shape("rectangle")

bs = BottomSheet()
bs.set_selection_type("20")
bs.set_button_2_text("Save")
bs.set_preselected(True)
ot = TextItem()
ot.set_text("Which gender(s) are you interested to meet?")
bs.set_title(ot)
ot = TextItem()
ot.set_text("Select as many as you want")
bs.set_subtitle_1(ot)
bs.set_screen_type("criteria_screen")
bs.set_layout("v_list_with_separator")

bsops = []
bso = Option()
bso.set_option_id("3.1")
bsot = TextItem()
bsot.set_text("Trans-man")
bso.set_option_title(bsot)
bso.set_option_type("list_item_2")
bsops.append(bso)
bso = Option()
bso.set_option_id("3.2")
bsot = TextItem()
bsot.set_text("Trans-woman")
bso.set_option_title(bsot)
bso.set_option_type("list_item_2")
bsops.append(bso)
bso = Option()
bso.set_option_id("3.3")
bsot = TextItem()
bsot.set_text("Genderqueer")
bso.set_option_title(bsot)
bso.set_option_type("list_item_2")
bsops.append(bso)
bso = Option()
bso.set_option_id("3.4")
bsot = TextItem()
bsot.set_text("Agender")
bso.set_option_title(bsot)
bso.set_option_type("list_item_2")
bsops.append(bso)
bso = Option()
bso.set_option_id("3.5")
bsot = TextItem()
bsot.set_text("Genderless")
bso.set_option_title(bsot)
bso.set_option_type("list_item_2")
bsops.append(bso)
bso = Option()
bso.set_option_id("3.6")
bsot = TextItem()
bsot.set_text("Non-binary")
bso.set_option_title(bsot)
bso.set_option_type("list_item_2")
bsops.append(bso)
bso = Option()
bso.set_option_id("3.7")
bsot = TextItem()
bsot.set_text("Third gender")
bso.set_option_title(bsot)
bso.set_option_type("list_item_2")
bsops.append(bso)
bso = Option()
bso.set_option_id("3.8")
bsot = TextItem()
bsot.set_text("Two-spirit")
bso.set_option_title(bsot)
bso.set_option_type("list_item_2")
bsops.append(bso)
bso = Option()
bso.set_option_id("3.9")
bsot = TextItem()
bsot.set_text("Bigender")
bso.set_option_title(bsot)
bso.set_option_type("list_item_2")
bsops.append(bso)
bso = Option()
bso.set_option_id("3.10")
bsot = TextItem()
bsot.set_text("Others")
bso.set_option_title(bsot)
bso.set_option_type("list_item_2")
bsops.append(bso)
bs.set_options(bsops)
o.set_bottom_sheet(bs)

options.append(o)


ops = options.__str__()
a.set_options(ops)
rep = a.__str__()