from Question import *
a = Question()
a.set_sort_key("16")
a.set_partition_key("questions")

a.set_question_id("16")
at = TextItem()
at.set_text("Do you have any disability or serious illness?")
a.set_title(at)
at = TextItem()
at.set_text("Ones that impact day-to-day life and that you would like your partner to know of. This will help me match you to the right supportive partner.")
a.set_subtitle(at)
a.set_subtitle_2("")
a.set_warning("")
a.set_warning_type("")
a.set_question_type("Chronic_Illness")
a.set_option_type("list_cell_snippet")
a.set_selection_type("single_selection")
a.set_progress(f"{int(a.question_id)/TOTAL_QUESTIONS :.2f}")
a.set_conditions("")
a.set_next_button_text("Next")

options = []
o = Options()
o.set_option_id("1")
ot = TextItem()
ot.set_text("No")
ot.set_left_icon("eddb")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("2")
ot = TextItem()
ot.set_text("Yes")
ot.set_left_icon("ea30")
o.set_option_title(ot)
of = TextField()
of.set_isMultiLine(True)
oft = TextItem()
oft.set_text("Please share a bit more...")
of.set_placeholder(oft)
o.set_option_text_field(of)
options.append(o)


ops = options.__str__()
a.set_options(ops)
rep = a.__str__()