from Question import *
a = Question()
a.set_sort_key("23")
a.set_partition_key("questions")
a.set_question_id(a.sort_key)
at = TextItem()
at.set_text("What's your religion?")
a.set_title(at)
a.set_subtitle("")
a.set_subtitle_2("")
a.set_alert("While your religious beliefs are personal, they can be a source of comfort, shared values, and traditions. Sharing it lets us find matches who respects your beliefs")
a.set_alert_type("info")
a.set_question_type("question_religion")
a.set_layout("v_list")
a.set_selection_type("1")
a.set_progress(f"{int(a.question_id)/TOTAL_QUESTIONS :.2f}")
a.set_conditions("")
a.set_next_button_text("Next")
a.set_next_button_id(f"qs_{a.question_id}_next")

options = []
o = Option()
o.set_option_id("1")
o.set_option_type("option_card")
ot = TextItem()
ot.set_text("Hindu")
o.set_option_title(ot)
options.append(o)
o = Option()
o.set_option_id("2")
o.set_option_type("option_card")
ot = TextItem()
ot.set_text("Muslim")
o.set_option_title(ot)
options.append(o)
o = Option()
o.set_option_id("3")
o.set_option_type("option_card")
ot = TextItem()
ot.set_text("Christian")
o.set_option_title(ot)
options.append(o)
o = Option()
o.set_option_id("4")
o.set_option_type("option_card")
ot = TextItem()
ot.set_text("Jain")
o.set_option_title(ot)
options.append(o)
o = Option()

o.set_option_id("5")
o.set_option_type("option_card")
ot = TextItem()
ot.set_text("Sikh")
o.set_option_title(ot)
bs = BottomSheet()
bs.set_id("sikh_religion_bs")
bs.set_selection_type("1")
bs.set_button_2_text("Save")
bs.set_button_2_id("sikh_religion_bs_save")
ot = TextItem()
ot.set_text("Do you identify yourself as a Puraan Gursikh?")
bs.set_title(ot)
bs.set_screen_type("criteria_screen")
bs.set_layout("v_list")
bsops = []
bso = Option()
bso.set_option_id("5.1")
bsot = TextItem()
bsot.set_text("Yes")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bso = Option()
bso.set_option_id("5.2")
bsot = TextItem()
bsot.set_text("No")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bso = Option()
bso.set_option_id("5.3")
bsot = TextItem()
bsot.set_text("I'm not sure")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bs.set_options(bsops)
o.set_bottom_sheet(bs)
options.append(o)

o = Option()
o.set_option_id("6")
o.set_option_type("option_card")
ot = TextItem()
ot.set_text("Buddhist")
o.set_option_title(ot)
options.append(o)
o = Option()
o.set_option_id("7")
o.set_option_type("option_card")
ot = TextItem()
ot.set_text("Jewish")
o.set_option_title(ot)
options.append(o)


ops = options.__str__()
a.set_options(ops)
rep = a.__str__()