from Question import *
a = Question()
a.set_sort_key("18")
a.set_partition_key("questions")

a.set_question_id("18")
at = TextItem()
at.set_text("What do you do for a living?")
a.set_title(at)
a.set_subtitle("")
a.set_subtitle_2("")
a.set_alert("")
a.set_alert_type("")
a.set_question_type("Profession")
a.set_option_type("list_cell_snippet")
a.set_selection_type("single_selection")
a.set_progress(f"{int(a.question_id)/TOTAL_QUESTIONS :.2f}")
a.set_conditions("")
a.set_next_button_text("Next")

options = []
o = Options()
o.set_option_id("1")
ot = TextItem()
ot.set_text("Business Management / Finance")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("2")
ot = TextItem()
ot.set_text("Software Engineering / IT")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("3")
ot = TextItem()
ot.set_text("Core Engineering / Manufacturing")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("4")
ot = TextItem()
ot.set_text("HR / Recruiting")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("5")
ot = TextItem()
ot.set_text("Doctor / Dentist")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("6")
ot = TextItem()
ot.set_text("Psychologist / Physiotherapist / Pharmacist")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("7")
ot = TextItem()
ot.set_text("Nurse / Compounder / Lab Technician")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("8")
ot = TextItem()
ot.set_text("Lawyer / Judiciary")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("9")
ot = TextItem()
ot.set_text("Architect / Interior Decorator")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("10")
ot = TextItem()
ot.set_text("Builder / Contractor / Real estate")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("11")
ot = TextItem()
ot.set_text("Teacher / Professor")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("12")
ot = TextItem()
ot.set_text("Admin / Secretarial")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("13")
ot = TextItem()
ot.set_text("Sports / eSports professional")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("14")
ot = TextItem()
ot.set_text("Advertising / Creative / Design professional")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("15")
ot = TextItem()
ot.set_text("Fashion Designer")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("16")
ot = TextItem()
ot.set_text("Stylist")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("17")
ot = TextItem()
ot.set_text("Event management / wedding planner")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("18")
ot = TextItem()
ot.set_text("Not for Profit / Social Work")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("19")
ot = TextItem()
ot.set_text("Public Policy")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("20")
ot = TextItem()
ot.set_text("Journalist / PR professional")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("21")
ot = TextItem()
ot.set_text("Artist / Dancer / Author / Musician / Historian / Dramatist")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("22")
ot = TextItem()
ot.set_text("Scientist / Mathematician")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("23")
ot = TextItem()
ot.set_text("Retail shop owner / Distributor / Wholesaler")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("24")
ot = TextItem()
ot.set_text("Shop staff / Field salesperson")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("25")
ot = TextItem()
ot.set_text("Pilot / Merchant Navyary")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("26")
ot = TextItem()
ot.set_text("Air hostess / Purser / Airline staff")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("27")
ot = TextItem()
ot.set_text("Travel agent / tourism professional")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("28")
ot = TextItem()
ot.set_text("Actor/Model/Social Influencer")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("29")
ot = TextItem()
ot.set_text("Film / TV Director / Producer / Technician")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("30")
ot = TextItem()
ot.set_text("Chef / Restaurateur / Hotel Management")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("31")
ot = TextItem()
ot.set_text("Agriculture")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("32")
ot = TextItem()
ot.set_text("Armed Forces / Law Enforcement")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("33")
ot = TextItem()
ot.set_text("Politician / political party worker")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("34")
ot = TextItem()
ot.set_text("Bureaucrat")
o.set_option_title(ot)
options.append(o)

o = Options()
o.set_option_id("35")
ot = TextItem()
ot.set_text("Other (eg Matchmaker, Detective, Astrologer etc)")
o.set_option_title(ot)
of = TextField()
of.set_isMultiLine(False)
oft = TextItem()
oft.set_text("Enter here...")
of.set_placeholder(oft)
o.set_option_text_field(of)
options.append(o)


ops = options.__str__()
a.set_options(ops)

## Add conditions
conditions = []
c = Conditions()
c.set_question_id("17")
c.set_option("1")
conditions.append(c)
c = Conditions()
c.set_question_id("17")
c.set_option("2")
conditions.append(c)
c = Conditions()
c.set_question_id("17")
c.set_option("3")
conditions.append(c)
c = Conditions()
c.set_question_id("17")
c.set_option("4")
conditions.append(c)
c = Conditions()
c.set_question_id("17")
c.set_option("5")
conditions.append(c)
conditions = conditions.__str__()
a.set_conditions(conditions)

rep = a.__str__()