from Question import *
a = Question()
a.set_sort_key("24")
a.set_partition_key("questions")
a.set_question_id(a.sort_key)
at = TextItem()
at.set_text("Which community do you belong to?")
a.set_title(at)
at = TextItem()
at.set_text("Select as many as you want")
a.set_subtitle(at)
a.set_subtitle_2("")
a.set_alert("")
a.set_alert_type("info")
a.set_question_type("question_community")
a.set_layout("v_list")
a.set_selection_type("20")
a.set_progress(f"{int(a.question_id)/TOTAL_QUESTIONS :.2f}")
a.set_conditions("")
a.set_next_button_text("Next")
a.set_next_button_id(f"qs_{a.question_id}_next")

options = []
o = Option()
o.set_option_id("1")
o.set_option_type("option_card")
ot = TextItem()
ot.set_text("Not Indian, does not apply")
o.set_option_title(ot)
options.append(o)
o = Option()
o.set_option_id("2")
o.set_option_type("option_card")
ot = TextItem()
ot.set_text("Punjabi")
o.set_option_title(ot)
options.append(o)
o = Option()
o.set_option_id("3")
o.set_option_type("option_card")
ot = TextItem()
ot.set_text("Marathi")
o.set_option_title(ot)
options.append(o)
o = Option()
o.set_option_id("4")
o.set_option_type("option_card")
ot = TextItem()
ot.set_text("Gujarati")
o.set_option_title(ot)
options.append(o)
o = Option()
o.set_option_id("5")
o.set_option_type("option_card")
ot = TextItem()
ot.set_text("Bengali")
o.set_option_title(ot)
options.append(o)
o = Option()
o.set_option_id("6")
o.set_option_type("option_card")
ot = TextItem()
ot.set_text("Odia")
o.set_option_title(ot)
options.append(o)
o = Option()
o.set_option_id("7")
o.set_option_type("option_card")
ot = TextItem()
ot.set_text("Bihari/Jharkhandi")
o.set_option_title(ot)
options.append(o)
o = Option()
o.set_option_id("8")
o.set_option_type("option_card")
ot = TextItem()
ot.set_text("UP/Uttrakhandi")
o.set_option_title(ot)
options.append(o)
o = Option()
o.set_option_id("9")
o.set_option_type("option_card")
ot = TextItem()
ot.set_text("MPite/Chattisgarhi")
o.set_option_title(ot)
options.append(o)
o = Option()
o.set_option_id("10")
o.set_option_type("option_card")
ot = TextItem()
ot.set_text("Kashmiri")
o.set_option_title(ot)
options.append(o)
o = Option()
o.set_option_id("11")
o.set_option_type("option_card")
ot = TextItem()
ot.set_text("Himachali")
o.set_option_title(ot)
options.append(o)
o = Option()
o.set_option_id("12")
o.set_option_type("option_card")
ot = TextItem()
ot.set_text("Haryanvi")
o.set_option_title(ot)
options.append(o)
o = Option()
o.set_option_id("13")
o.set_option_type("option_card")
ot = TextItem()
ot.set_text("Assamese")
o.set_option_title(ot)
options.append(o)
o = Option()
o.set_option_id("14")
o.set_option_type("option_card")
ot = TextItem()
ot.set_text("Telugu")
o.set_option_title(ot)
options.append(o)
o = Option()
o.set_option_id("15")
o.set_option_type("option_card")
ot = TextItem()
ot.set_text("Kannadiga")
o.set_option_title(ot)
options.append(o)
o = Option()
o.set_option_id("16")
o.set_option_type("option_card")
ot = TextItem()
ot.set_text("Tulu")
o.set_option_title(ot)
options.append(o)
o = Option()
o.set_option_id("17")
o.set_option_type("option_card")
ot = TextItem()
ot.set_text("Malayali")
o.set_option_title(ot)
options.append(o)
o = Option()
o.set_option_id("18")
o.set_option_type("option_card")
ot = TextItem()
ot.set_text("Konkani")
o.set_option_title(ot)
options.append(o)
o = Option()
o.set_option_id("19")
o.set_option_type("option_card")
ot = TextItem()
ot.set_text("Rajput")
o.set_option_title(ot)
options.append(o)
o = Option()
o.set_option_id("20")
o.set_option_type("option_card")
ot = TextItem()
ot.set_text("Sindhi")
o.set_option_title(ot)
options.append(o)
o = Option()
o.set_option_id("21")
o.set_option_type("option_card")
ot = TextItem()
ot.set_text("Marwari")
o.set_option_title(ot)
options.append(o)

o = Option()
o.set_option_id("22")
o.set_option_type("option_card")
ot = TextItem()
ot.set_text("Other")
o.set_option_title(ot)
of = TextField()
of.set_isMultiLine(True)
oft = TextItem()
oft.set_text("Enter your caste...")
of.set_placeholder(oft)
o.set_option_text_field(of)
options.append(o)


## Add conditions
conditions = []
c = Conditions()
c.set_question_id("3")
c.set_option("1,2")
conditions.append(c)
conditions = conditions.__str__()
a.set_conditions(conditions)


ops = options.__str__()
a.set_options(ops)
rep = a.__str__()