from Question import *
a = Question()
a.set_sort_key("24")
a.set_partition_key("questions")

a.set_question_id("24")
at = TextItem()
at.set_text("What's your caste?")
a.set_title(at)
a.set_subtitle("")
a.set_subtitle_2("")
a.set_alert("This thing may not matter to you, but I want to be inclusive and respectful of individual choice, since these may matter to some members or their famalies.")
a.set_alert_type("info")
a.set_question_type("Caste")
a.set_layout("v_list")
a.set_selection_type("1")
a.set_progress(f"{int(a.question_id)/TOTAL_QUESTIONS :.2f}")
a.set_conditions("")
a.set_next_button_text("Next")

options = []
o = Option()
o.set_option_id("1")
o.set_option_type("option_card")
ot = TextItem()
ot.set_text("Don't know or don't care")
o.set_option_title(ot)
options.append(o)
o = Option()
o.set_option_id("2")
o.set_option_type("option_card")
ot = TextItem()
ot.set_text("Hindu")
o.set_option_title(ot)
options.append(o)
o = Option()
o.set_option_id("3")
o.set_option_type("option_card")
ot = TextItem()
ot.set_text("Muslim")
o.set_option_title(ot)
options.append(o)
o = Option()
o.set_option_id("4")
o.set_option_type("option_card")
ot = TextItem()
ot.set_text("Christian")
o.set_option_title(ot)
options.append(o)
o = Option()
o.set_option_id("5")
o.set_option_type("option_card")
ot = TextItem()
ot.set_text("Jain")
o.set_option_title(ot)
options.append(o)
o = Option()
o.set_option_id("6")
o.set_option_type("option_card")
ot = TextItem()
ot.set_text("Sikh")
o.set_option_title(ot)
options.append(o)
o = Option()
o.set_option_id("7")
o.set_option_type("option_card")
ot = TextItem()
ot.set_text("Buddhist")
o.set_option_title(ot)
options.append(o)
o = Option()
o.set_option_id("8")
o.set_option_type("option_card")
ot = TextItem()
ot.set_text("Jewish")
o.set_option_title(ot)
options.append(o)


## Add conditions
conditions = []
c = Conditions()
c.set_question_id("3")
c.set_option("1,2")
conditions.append(c)
conditions = conditions.__str__()
a.set_conditions(conditions)


ops = options.__str__()
a.set_options(ops)
rep = a.__str__()