from Question import *
a = Question()
a.set_sort_key("25")
a.set_partition_key("questions")

a.set_question_id("25")
at = TextItem()
at.set_text("Which community do you belong to?")
a.set_title(at)
at = TextItem()
at.set_text("Select as many as you want")
a.set_subtitle(at)
a.set_subtitle_2("")
a.set_alert("")
a.set_alert_type("info")
a.set_question_type("Community")
a.set_option_type("card_v_list")
a.set_selection_type("multi_selection")
a.set_progress(f"{int(a.question_id)/TOTAL_QUESTIONS :.2f}")
a.set_conditions("")
a.set_next_button_text("Next")

options = []
o = Options()
o.set_option_id("1")
ot = TextItem()
ot.set_text("Not Indian, does not apply")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("2")
ot = TextItem()
ot.set_text("Punjabi")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("3")
ot = TextItem()
ot.set_text("Marathi")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("4")
ot = TextItem()
ot.set_text("Gujarati")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("5")
ot = TextItem()
ot.set_text("Bengali")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("6")
ot = TextItem()
ot.set_text("Odia")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("7")
ot = TextItem()
ot.set_text("Bihari/Jharkhandi")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("8")
ot = TextItem()
ot.set_text("UP/Uttrakhandi")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("9")
ot = TextItem()
ot.set_text("MPite/Chattisgarhi")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("10")
ot = TextItem()
ot.set_text("Kashmiri")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("11")
ot = TextItem()
ot.set_text("Himachali")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("12")
ot = TextItem()
ot.set_text("Haryanvi")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("13")
ot = TextItem()
ot.set_text("Assamese")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("14")
ot = TextItem()
ot.set_text("Telugu")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("15")
ot = TextItem()
ot.set_text("Kannadiga")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("16")
ot = TextItem()
ot.set_text("Tulu")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("17")
ot = TextItem()
ot.set_text("Malayali")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("18")
ot = TextItem()
ot.set_text("Konkani")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("19")
ot = TextItem()
ot.set_text("Rajput")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("20")
ot = TextItem()
ot.set_text("Sindhi")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("21")
ot = TextItem()
ot.set_text("Marwari")
o.set_option_title(ot)
options.append(o)

o = Options()
o.set_option_id("22")
ot = TextItem()
ot.set_text("Other")
o.set_option_title(ot)
of = TextField()
of.set_isMultiLine(True)
oft = TextItem()
oft.set_text("Enter your caste...")
of.set_placeholder(oft)
o.set_option_text_field(of)
options.append(o)


## Add conditions
conditions = []
c = Conditions()
c.set_question_id("3")
c.set_option("1,2")
conditions.append(c)
conditions = conditions.__str__()
a.set_conditions(conditions)


ops = options.__str__()
a.set_options(ops)
rep = a.__str__()