from Question import *
a = Question()
a.set_sort_key("25")
a.set_partition_key("questions")
a.set_question_id(a.sort_key)
at = TextItem()
at.set_text("What's your caste?")
a.set_title(at)
a.set_subtitle("")
a.set_subtitle_2("")
a.set_alert("This thing may not matter to you, but I want to be inclusive and respectful of individual choice, since these may matter to some members or their famalies.")
a.set_alert_type("info")
a.set_question_type("question_caste")
a.set_layout("search_fields")
a.set_selection_type("1")
a.set_progress(f"{int(a.question_id)/TOTAL_QUESTIONS :.2f}")
a.set_conditions("")
a.set_next_button_text("Next")
a.set_next_button_id(f"qs_{a.question_id}_next")
a.set_skip_button_text("I don't know / don't care")
a.set_skip_button_id(f"qs_{a.question_id}_skip")

options = []
o = Option()
o.set_option_id("1")
o.set_option_type("option_card")
ot = TextItem()
ot.set_text("Your caste")
o.set_option_title(ot)
bs = BottomSheet()
bs.set_selection_type("1")
ot = TextItem()
ot.set_text("Select your caste")
bs.set_title(ot)
bs.set_screen_type("caste_selector_screen")
o.set_bottom_sheet(bs)
options.append(o)

o = Option()
o.set_option_id("2")
o.set_option_type("option_card")
ot = TextItem()
ot.set_text("Enter your gothra…")
o.set_option_title(ot)
bs = BottomSheet()
bs.set_selection_type("1")
ot = TextItem()
ot.set_text("Select your gotra")
bs.set_title(ot)
bs.set_screen_type("gothra_selector_screen")
o.set_bottom_sheet(bs)
options.append(o)


## Add conditions
conditions = []
c = Conditions()
c.set_question_id("3")
c.set_option("1,2")
conditions.append(c)
c = Conditions()
c.set_question_id("23")
c.set_option("1")
conditions.append(c)
conditions = conditions.__str__()
a.set_conditions(conditions)


ops = options.__str__()
a.set_options(ops)
rep = a.__str__()