from Question import *
a = Question()
a.set_sort_key("22")
a.set_partition_key("questions")

a.set_question_id("22")
at = TextItem()
at.set_text("Where were you born?")
a.set_title(at)
a.set_subtitle("")
a.set_subtitle_2("")
a.set_alert("Some Members appreciate the predictive power of Vedic Science (horoscopes), while others may find it annoying! Wherever you stand, I don't want you to lose out on someone fabulous, so please play along and allow me to surprise you!")
a.set_alert_type("info")
a.set_question_type("Birthplace")
a.set_layout("option_card_text_field_snippet")
a.set_selection_type("single_selection")
a.set_progress(f"{int(a.question_id)/TOTAL_QUESTIONS :.2f}")
a.set_conditions("")
a.set_next_button_text("Next")

options = []
o = Option()
o.set_option_id("1")
of = TextField()
of.set_left_icon("ebdd")
of.set_isMultiLine(False)
oft = TextItem()
oft.set_text("Search your city")
of.set_placeholder(oft)
oft = TextItem()
oft.set_text("Start typing...")
of.placeholderOnEditing(oft)
o.set_option_text_field(of)
options.append(o)

ops = options.__str__()
a.set_options(ops)
rep = a.__str__()