from Question import *
a = Question()
a.set_sort_key("partner_criteria_date")
a.set_partition_key("questions")

a.set_question_id("29")
at = TextItem()
at.set_text("CASUAL Do any of these partner criteria matter to you?")
a.set_title(at)
at = TextItem()
at.set_text("Not shown on your profile")
at.set_left_icon("ead3")
a.set_subtitle(at)
a.set_subtitle_2("")
a.set_alert("I will show you profiles that meet your criteria, unless there are none that do. Don't be too strict and miss out on a great meeting, you can always add more later!")
a.set_alert_type("warning")
a.set_question_type("partner_criteria")
a.set_layout("v_list_with_separator")
a.set_selection_type("30")
a.set_progress(f"{int(28)/TOTAL_QUESTIONS :.2f}")
# a.set_progress(f"{TOTAL_QUESTIONS/TOTAL_QUESTIONS :.2f}")
a.set_next_button_text("Next")
a.set_next_button_id(f"qs_{a.question_id}_next")

options = []
o = Option()
o.set_option_id("1")
o.set_option_type("list_item_2")
ot = TextItem()
ot.set_text("Age")
o.set_option_title(ot)
bs = BottomSheet()
bs.set_selection_type("1")
bs.set_button_2_text("Add criteria")
bs.set_button_2_left_icon("ec86")
ot = TextItem()
ot.set_text("Partner's age")
bs.set_title(ot)
bs.set_screen_type("age_selector_screen")
bs.set_layout("range_selector")
bs.set_alert("My friendly advice - keep a wide enough range to ensure you don't miss out on great partners")
bs.set_alert_type("warning")
o.set_bottom_sheet(bs)
options.append(o)

o = Option()
o.set_option_id("2")
o.set_option_type("list_item_2")
ot = TextItem()
ot.set_text("Marital Status")
o.set_option_title(ot)
bs = BottomSheet()
bs.set_selection_type("20")
bs.set_preselected(True)
bs.set_button_2_text("Add criteria")
bs.set_button_2_left_icon("ec86")
ot = TextItem()
ot.set_text("Partner's marital status")
bs.set_title(ot)
bs.set_screen_type("criteria_screen")
bs.set_layout("v_list")
bsops = []
bso = Option()
bso.set_option_id("2.1")
bsot = TextItem()
bsot.set_text("Never married")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bso = Option()
bso.set_option_id("2.2")
bsot = TextItem()
bsot.set_text("Divorced")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bso = Option()
bso.set_option_id("2.3")
bsot = TextItem()
bsot.set_text("Separated / divorce in progress")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bso = Option()
bso.set_option_id("2.4")
bsot = TextItem()
bsot.set_text("Widowed")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bs.set_options(bsops)
o.set_bottom_sheet(bs)
options.append(o)

o = Option()
o.set_option_id("3")
o.set_option_type("list_item_2")
ot = TextItem()
ot.set_text("Children")
o.set_option_title(ot)
bs = BottomSheet()
bs.set_selection_type("20")
bs.set_preselected(True)
bs.set_button_2_text("Add criteria")
bs.set_button_2_left_icon("ec86")
ot = TextItem()
ot.set_text("Partner's children")
bs.set_title(ot)
bs.set_screen_type("criteria_screen")
bs.set_layout("v_list")
bsops = []
bso = Option()
bso.set_option_id("3.1")
bsot = TextItem()
bsot.set_text("Wants someday")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bso = Option()
bso.set_option_id("3.2")
bsot = TextItem()
bsot.set_text("Doesn't want")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bso = Option()
bso.set_option_id("3.3")
bsot = TextItem()
bsot.set_text("Has and wants more")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bso = Option()
bso.set_option_id("3.4")
bsot = TextItem()
bsot.set_text("Has and doesn't want more")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bs.set_options(bsops)
o.set_bottom_sheet(bs)
options.append(o)

o = Option()
o.set_option_id("4")
o.set_option_type("list_item_2")
ot = TextItem()
ot.set_text("Drinking")
o.set_option_title(ot)
bs = BottomSheet()
bs.set_selection_type("20")
bs.set_preselected(True)
bs.set_button_2_text("Add criteria")
bs.set_button_2_left_icon("ec86")
ot = TextItem()
ot.set_text("Partner's drinking")
bs.set_title(ot)
bs.set_screen_type("criteria_screen")
bs.set_layout("v_list")
bsops = []
bso = Option()
bso.set_option_id("4.1")
bsot = TextItem()
bsot.set_text("Never")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bso = Option()
bso.set_option_id("4.2")
bsot = TextItem()
bsot.set_text("Sometimes/Socially")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bso = Option()
bso.set_option_id("4.3")
bsot = TextItem()
bsot.set_text("Regularly")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bs.set_options(bsops)
o.set_bottom_sheet(bs)
options.append(o)

o = Option()
o.set_option_id("5")
o.set_option_type("list_item_2")
ot = TextItem()
ot.set_text("Smoking")
o.set_option_title(ot)
bs = BottomSheet()
bs.set_selection_type("20")
bs.set_preselected(True)
bs.set_button_2_text("Add criteria")
bs.set_button_2_left_icon("ec86")
ot = TextItem()
ot.set_text("Partner's smoking")
bs.set_title(ot)
bs.set_screen_type("criteria_screen")
bs.set_layout("v_list")
bsops = []
bso = Option()
bso.set_option_id("5.1")
bsot = TextItem()
bsot.set_text("Never")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bso = Option()
bso.set_option_id("5.2")
bsot = TextItem()
bsot.set_text("Sometimes/Socially")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bso = Option()
bso.set_option_id("5.3")
bsot = TextItem()
bsot.set_text("Regularly")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bs.set_options(bsops)
o.set_bottom_sheet(bs)
options.append(o)

o = Option()
o.set_option_id("6")
o.set_option_type("list_item_2")
ot = TextItem()
ot.set_text("Marijuana")
o.set_option_title(ot)
bs = BottomSheet()
bs.set_selection_type("20")
bs.set_preselected(True)
bs.set_button_2_text("Add criteria")
bs.set_button_2_left_icon("ec86")
ot = TextItem()
ot.set_text("Partner's marijuana use")
bs.set_title(ot)
bs.set_screen_type("criteria_screen")
bs.set_layout("v_list")
bsops = []
bso = Option()
bso.set_option_id("6.1")
bsot = TextItem()
bsot.set_text("Never")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bso = Option()
bso.set_option_id("6.2")
bsot = TextItem()
bsot.set_text("Someone who might do it")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bs.set_options(bsops)
o.set_bottom_sheet(bs)
options.append(o)

o = Option()
o.set_option_id("7")
o.set_option_type("list_item_2")
ot = TextItem()
ot.set_text("Other drugs")
o.set_option_title(ot)
bs = BottomSheet()
bs.set_selection_type("20")
bs.set_preselected(True)
bs.set_button_2_text("Add criteria")
bs.set_button_2_left_icon("ec86")
ot = TextItem()
ot.set_text("Partner's other drug use")
bs.set_title(ot)
bs.set_screen_type("criteria_screen")
bs.set_layout("v_list")
bsops = []
bso = Option()
bso.set_option_id("7.1")
bsot = TextItem()
bsot.set_text("Never")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bso = Option()
bso.set_option_id("7.2")
bsot = TextItem()
bsot.set_text("Someone who might do it")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bs.set_options(bsops)
o.set_bottom_sheet(bs)
options.append(o)

o = Option()
o.set_option_id("8")
o.set_option_type("list_item_2")
ot = TextItem()
ot.set_text("Diet")
o.set_option_title(ot)
bs = BottomSheet()
bs.set_selection_type("20")
bs.set_preselected(True)
bs.set_button_2_text("Add criteria")
bs.set_button_2_left_icon("ec86")
ot = TextItem()
ot.set_text("Partner's diet")
bs.set_title(ot)
ot = TextItem()
ot.set_text("Select as many as you want")
bs.set_subtitle_1(ot)
bs.set_screen_type("criteria_screen")
bs.set_layout("v_list")
bsops = []
bso = Option()
bso.set_option_id("8.1")
bsot = TextItem()
bsot.set_text("Non vegetarian")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bso = Option()
bso.set_option_id("8.2")
bsot = TextItem()
bsot.set_text("Vegetarian")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bso = Option()
bso.set_option_id("8.3")
bsot = TextItem()
bsot.set_text("Eggetarian")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bso = Option()
bso.set_option_id("8.4")
bsot = TextItem()
bsot.set_text("Pescetarian")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bso = Option()
bso.set_option_id("8.5")
bsot = TextItem()
bsot.set_text("Jain")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bso = Option()
bso.set_option_id("8.6")
bsot = TextItem()
bsot.set_text("Vegan")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bs.set_options(bsops)
o.set_bottom_sheet(bs)
options.append(o)

o = Option()
o.set_option_id("9")
o.set_option_type("list_item_2")
ot = TextItem()
ot.set_text("City")
o.set_option_title(ot)
bs = BottomSheet()
bs.set_selection_type("20")
bs.set_preselected(True)
bs.set_button_2_text("Add criteria")
bs.set_button_2_left_icon("ec86")
ot = TextItem()
ot.set_text("Partner's location")
bs.set_title(ot)
bs.set_screen_type("criteria_screen")
bs.set_layout("v_list")
bsops = []
bso = Option()
bso.set_option_id("9.1")
bsot = TextItem()
bsot.set_text("Any city in the world")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bso = Option()
bso.set_option_id("9.2")
bsot = TextItem()
bsot.set_text("Any city in India")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bso = Option()
bso.set_option_id("9.3")
bsot = TextItem()
bsot.set_text("Mumbai only")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bso = Option()
bso.set_option_id("9.4")
bsot = TextItem()
bsot.set_text("Delhi NCR only")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bs.set_options(bsops)
o.set_bottom_sheet(bs)
options.append(o)

o = Option()
o.set_option_id("10")
o.set_option_type("list_item_2")
ot = TextItem()
ot.set_text("Religion")
o.set_option_title(ot)
bs = BottomSheet()
bs.set_selection_type("20")
bs.set_preselected(True)
bs.set_button_2_text("Add criteria")
bs.set_button_2_left_icon("ec86")
ot = TextItem()
ot.set_text("Partner's religion")
bs.set_title(ot)
bs.set_screen_type("criteria_screen")
bs.set_layout("v_list")
bsops = []
bso = Option()
bso.set_option_id("10.1")
bsot = TextItem()
bsot.set_text("Hindu")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bso = Option()
bso.set_option_id("10.2")
bsot = TextItem()
bsot.set_text("Muslim")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bso = Option()
bso.set_option_id("10.3")
bsot = TextItem()
bsot.set_text("Christian")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bso = Option()
bso.set_option_id("10.4")
bsot = TextItem()
bsot.set_text("Jain")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bso = Option()
bso.set_option_id("10.5")
bsot = TextItem()
bsot.set_text("Sikh (Puraan Gursikh)")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bso = Option()
bso.set_option_id("10.6")
bsot = TextItem()
bsot.set_text("Sikh (not Puraan Gursikh)")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bso = Option()
bso.set_option_id("10.7")
bsot = TextItem()
bsot.set_text("Parsi")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bso = Option()
bso.set_option_id("10.8")
bsot = TextItem()
bsot.set_text("Buddhist")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bso = Option()
bso.set_option_id("10.9")
bsot = TextItem()
bsot.set_text("Jewish")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bso = Option()
bso.set_option_id("10.10")
bsot = TextItem()
bsot.set_text("Other")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bs.set_options(bsops)
o.set_bottom_sheet(bs)
options.append(o)

o = Option()
o.set_option_id("11")
o.set_option_type("list_item_2")
ot = TextItem()
ot.set_text("Community")
o.set_option_title(ot)
options.append(o)

o = Option()
o.set_option_id("12")
o.set_option_type("list_item_2")
ot = TextItem()
ot.set_text("Caste")
o.set_option_title(ot)
bs = BottomSheet()
bs.set_selection_type("1")
bs.set_button_2_text("Add criteria")
bs.set_button_2_left_icon("ec86")
ot = TextItem()
ot.set_text("Partner's caste")
bs.set_title(ot)
bs.set_screen_type("criteria_screen")
bs.set_layout("v_list")
bsops = []
bso = Option()
bso.set_option_id("12.1")
bsot = TextItem()
bsot.set_text("Same caste, same gothra")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bso = Option()
bso.set_option_id("12.2")
bsot = TextItem()
bsot.set_text("Same caste, different gothra")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bso = Option()
bso.set_option_id("12.3")
bsot = TextItem()
bsot.set_text("Different caste")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bs.set_options(bsops)
o.set_bottom_sheet(bs)
options.append(o)

o = Option()
o.set_option_id("13")
o.set_option_type("list_item_2")
ot = TextItem()
ot.set_text("Employment")
o.set_option_title(ot)
options.append(o)

o = Option()
o.set_option_id("14")
o.set_option_type("list_item_2")
ot = TextItem()
ot.set_text("Religious View")
o.set_option_title(ot)
bs = BottomSheet()
bs.set_selection_type("1")
bs.set_button_2_text("Add criteria")
bs.set_button_2_left_icon("ec86")
ot = TextItem()
ot.set_text("Partner's religious view")
bs.set_title(ot)
bs.set_screen_type("criteria_screen")
bs.set_layout("v_list")
bsops = []
bso = Option()
bso.set_option_id("14.1")
bsot = TextItem()
bsot.set_text("Religious")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bso = Option()
bso.set_option_id("14.2")
bsot = TextItem()
bsot.set_text("Spiritual, but not Religious")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bso = Option()
bso.set_option_id("14.3")
bsot = TextItem()
bsot.set_text("Neither of these")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bs.set_options(bsops)
o.set_bottom_sheet(bs)
options.append(o)

o = Option()
o.set_option_id("15")
o.set_option_type("list_item_2")
ot = TextItem()
ot.set_text("Political leaning")
o.set_option_title(ot)
bs = BottomSheet()
bs.set_selection_type("1")
bs.set_button_2_text("Add criteria")
bs.set_button_2_left_icon("ec86")
ot = TextItem()
ot.set_text("Partner's political leaning")
bs.set_title(ot)
bs.set_screen_type("criteria_screen")
bs.set_layout("v_list")
bsops = []
bso = Option()
bso.set_option_id("15.1")
bsot = TextItem()
bsot.set_text("Socialist/Leftist")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bso = Option()
bso.set_option_id("15.2")
bsot = TextItem()
bsot.set_text("Rightist")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bso = Option()
bso.set_option_id("15.3")
bsot = TextItem()
bsot.set_text("Moderate/Centrist")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bso = Option()
bso.set_option_id("15.4")
bsot = TextItem()
bsot.set_text("Apolitical")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bs.set_options(bsops)
o.set_bottom_sheet(bs)
options.append(o)

o = Option()
o.set_option_id("16")
o.set_option_type("list_item_2")
ot = TextItem()
ot.set_text("Height")
o.set_option_title(ot)
bs = BottomSheet()
bs.set_selection_type("1")
bs.set_button_2_text("Add criteria")
bs.set_button_2_left_icon("ec86")
ot = TextItem()
ot.set_text("Partner's height")
bs.set_title(ot)
bs.set_screen_type("criteria_screen")
bs.set_layout("v_list")
bsops = []
bso = Option()
bso.set_option_id("16.1")
bsot = TextItem()
bsot.set_text("More than 2 inches taller")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bso = Option()
bso.set_option_id("16.2")
bsot = TextItem()
bsot.set_text("Shorter or 2 inches taller")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bso = Option()
bso.set_option_id("16.3")
bsot = TextItem()
bsot.set_text("Only shorter than me")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bs.set_options(bsops)
o.set_bottom_sheet(bs)
options.append(o)

o = Option()
o.set_option_id("17")
o.set_option_type("list_item_2")
ot = TextItem()
ot.set_text("Horoscope")
o.set_option_title(ot)
bs = BottomSheet()
bs.set_selection_type("1")
bs.set_button_2_text("Add criteria")
bs.set_button_2_left_icon("ec86")
ot = TextItem()
ot.set_text("Partner's horoscope")
bs.set_title(ot)
bs.set_screen_type("criteria_screen")
bs.set_layout("v_list")
bsops = []
bso = Option()
bso.set_option_id("17.1")
bsot = TextItem()
bsot.set_text("Horoscopes must not match")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bso = Option()
bso.set_option_id("17.2")
bsot = TextItem()
bsot.set_text("Horoscopes must match")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bs.set_options(bsops)
o.set_bottom_sheet(bs)
options.append(o)


#Add conditions
conditions = []
c = Conditions()
c.set_question_id("3")
c.set_option("3,4")
conditions.append(c)
# c = Conditions()
# c.set_question_id("1")
# c.set_option("1")
# conditions.append(c)
conditions = conditions.__str__()
a.set_conditions(conditions)

ops = options.__str__()
a.set_options(ops)
rep = a.__str__()

