# Fun fact
from Question import *
a = Question()
a.set_sort_key("29")
a.set_partition_key("questions")

a.set_question_id("29")
at = TextItem()
at.set_text("Tell us a fun fact about yourself")
a.set_title(at)
at = TextItem()
at.set_text("We will share this with your partners on your first dates.")
a.set_subtitle(at)
a.set_subtitle_2("")
a.set_alert("")
a.set_alert_type("")
a.set_question_type("Fun_Fact")
a.set_option_type("option_text_field_snippet")
a.set_selection_type("single_selection")
a.set_progress(f"{int(a.question_id)/TOTAL_QUESTIONS :.2f}")
a.set_conditions("")
a.set_next_button_text("Next")

options = []
o = Options()
o.set_option_id("1")
of = TextField()
of.set_isMultiLine(True)
oft = TextItem()
oft.set_text('''eg., I'm the biggest Marvel fan''')
of.set_placeholder(oft)
oft = TextItem()
oft.set_text("Start typing...")
of.placeholderOnEditing(oft)
o.set_option_text_field(of)
options.append(o)

ops = options.__str__()
a.set_options(ops)
rep = a.__str__()



# from Question import *
# a = Question()
# a.set_sort_key("80")
# a.set_partition_key("questions")

# a.set_question_id("80")
# at = TextItem()
# at.set_text("Will you be comfortable with a partner who has a disability or serious illness?")
# a.set_title(at)
# a.set_subtitle("")
# a.set_subtitle_2("")
# a.set_alert("Being open to different experiences may lead to meaningful connections and a faster match with someone who truly understands and appreciates you. You will know about the nature of their disability/illness when you see their profile and can accordingly decide to meet or not")
# a.set_alert_type("info")
# a.set_question_type("Partner_Disability")
# a.set_option_type("card_v_list")
# a.set_selection_type("single_selection")
# a.set_progress(f"{int(a.question_id)/TOTAL_QUESTIONS :.2f}")
# a.set_conditions("")
# a.set_next_button_text("Next")

# options = []
# o = Options()
# o.set_option_id("1")
# ot = TextItem()
# ot.set_text("Yes")
# o.set_option_title(ot)
# options.append(o)
# o = Options()
# o.set_option_id("2")
# ot = TextItem()
# ot.set_text("No")
# o.set_option_title(ot)
# options.append(o)


# ops = options.__str__()
# a.set_options(ops)
# rep = a.__str__()