from Question import *
a = Question()
a.set_sort_key("3")
a.set_partition_key("questions")

a.set_question_id("3")
a.set_title("Who are you interested in meeting?")
a.set_subtitle("Select as many as you want")
a.set_subtitle_2("")
a.set_warning("")
a.set_warning_type("")
a.set_question_type("Gender_Preference")
a.set_option_type("image_card_view_snippet")
a.set_selection_type("multi_selection")
a.set_progress("0.13")
a.set_conditions("")
a.set_next_button_text("Next")

options = []
o = Options()
o.set_option_id("1")
o.set_option_image_url("Man")
o.set_option_text("Man")
options.append(o)
o = Options()
o.set_option_id("2")
o.set_option_image_url("Woman")
o.set_option_text("Woman")
options.append(o)
o = Options()
o.set_option_id("3")
o.set_option_image_url("OtherGender")
o.set_option_text("Other")
options.append(o)

ops = options.__str__()
a.set_options(ops)
rep = a.__str__()