# Fun fact
from Question import *
a = Question()
a.set_sort_key("30")
a.set_partition_key("questions")

a.set_question_id("30")
at = TextItem()
at.set_text("What's your Instagram username?")
a.set_title(at)
at = TextItem()
at.set_text("I will use this for verification purposes")
a.set_subtitle(at)
at = TextItem()
at.set_text("Not shown on your profile")
at.set_left_icon("ead3")
a.set_subtitle_2(at)
a.set_alert("")
a.set_alert_type("")
a.set_question_type("Instagram")
a.set_layout("option_card_text_field_snippet")
a.set_selection_type("single_selection")
a.set_progress(f"{int(a.question_id)/TOTAL_QUESTIONS :.2f}")
a.set_conditions("")
a.set_next_button_text("Next")

options = []
o = Option()
o.set_option_id("1")
of = TextField()
of.set_isMultiLine(True)
oft = TextItem()
oft.set_text("Instagram Username")
of.set_placeholder(oft)
oft = TextItem()
oft.set_text("Start typing...")
of.placeholderOnEditing(oft)
o.set_option_text_field(of)
options.append(o)

ops = options.__str__()
a.set_options(ops)
rep = a.__str__()

