# Fun fact
from Question import *
a = Question()
a.set_sort_key("31")
a.set_partition_key("questions")

a.set_question_id("31")
at = TextItem()
at.set_text("What's the name of your father?")
a.set_title(at)
at = TextItem()
at.set_text("Apparently every lifestyle app asks for this and I don't want to be left out! 🥺")
a.set_subtitle(at)
a.set_subtitle_2("")
a.set_alert("")
a.set_alert_type("")
a.set_question_type("Instagram")
a.set_layout("option_card_text_field_snippet")
a.set_selection_type("1")
a.set_progress(f"{int(a.question_id)/TOTAL_QUESTIONS :.2f}")
a.set_conditions("")
a.set_next_button_text("Next")

options = []
o = Option()
o.set_option_id("1")
of = TextField()
of.set_isMultiLine(True)
oft = TextItem()
oft.set_text("Father's full name")
of.set_placeholder(oft)
oft = TextItem()
oft.set_text("Start typing...")
of.placeholderOnEditing(oft)
o.set_option_text_field(of)
options.append(o)

ops = options.__str__()
a.set_options(ops)
rep = a.__str__()

