from Question import *
a = Question()
a.set_sort_key("32")
a.set_partition_key("questions")

a.set_question_id("32")
at = TextItem()
at.set_text("Do any of these partner criteria matter?")
a.set_title(at)
# at = TextItem()
# at.set_text("We will try to meet them.")
# a.set_subtitle(at)
at = TextItem()
at.set_text("Not shown on your profile")
at.set_left_icon("ead3")
a.set_subtitle(at)
a.set_alert("I will show you profiles that meet your criteria, unless there are none that do. Don't be too strict and miss out on a great meeting, you can always add more later!")
a.set_alert_type("info")
a.set_question_type("Partner_Criteria")
a.set_layout("v_list_2")
a.set_selection_type("1")
a.set_progress(f"{int(a.question_id)/TOTAL_QUESTIONS :.2f}")
a.set_conditions("")
a.set_next_button_text("Next")

options = []
o = Option()
o.set_option_id("1")
ot = TextItem()
ot.set_text("Age")
o.set_option_title(ot)
bs = BottomSheet()
ot = TextItem()
ot.set_text("Age")
bs.set_title(ot)
bs.set_button_2_text("Save")
bs.set_selection_type("1")
ops = []
opsi = Option()
opsi.set_option_id("1")
ot = TextItem()
ot.set_text("No Preference")
opsi.set_option_title(ot)
ops.append(opsi)
opsi = Option()
opsi.set_option_id("2")
ot = TextItem()
ot.set_text("Younger or upto 2 yrs older than me")
opsi.set_option_title(ot)
ops.append(opsi)
opsi = Option()
opsi.set_option_id("3")
ot = TextItem()
ot.set_text("Only younger than me")
opsi.set_option_title(ot)
ops.append(opsi)
opsi = Option()
opsi.set_option_id("4")
ot = TextItem()
ot.set_text("Older or upto 2 yrs younger than me")
opsi.set_option_title(ot)
ops.append(opsi)
opsi = Option()
opsi.set_option_id("5")
ot = TextItem()
ot.set_text("Only older than me")
opsi.set_option_title(ot)
ops.append(opsi)
bs.set_options(ops)
o.set_bottom_sheet(bs)
options.append(o)


o = Option()
o.set_option_id("2")
ot = TextItem()
ot.set_text("Marital Status")
o.set_option_title(ot)
bs = BottomSheet()
ot = TextItem()
ot.set_text("My partner's marital status can be")
bs.set_title(ot)
bs.set_button_2_text("Save")
bs.set_selection_type("20")
ops = []
opsi = Option()
opsi.set_option_id("1")
ot = TextItem()
ot.set_text("Never married")
opsi.set_option_title(ot)
ops.append(opsi)
opsi = Option()
opsi.set_option_id("2")
ot = TextItem()
ot.set_text("Divorced")
opsi.set_option_title(ot)
ops.append(opsi)
opsi = Option()
opsi.set_option_id("3")
ot = TextItem()
ot.set_text("Separated/divorce in progress")
opsi.set_option_title(ot)
ops.append(opsi)
opsi = Option()
opsi.set_option_id("4")
ot = TextItem()
ot.set_text("Widowed")
opsi.set_option_title(ot)
ops.append(opsi)
bs.set_options(ops)
o.set_bottom_sheet(bs)
options.append(o)

ops = options.__str__()
a.set_options(ops)
rep = a.__str__()