# Fun fact
from Question import *
a = Question()
a.set_sort_key("27")
a.set_partition_key("questions")

a.set_question_id("27")
at = TextItem()
at.set_text("Tell us a fun fact about yourself")
a.set_title(at)
at = TextItem()
at.set_text("We will share this with your partners on your first dates.")
a.set_subtitle(at)
a.set_subtitle_2("")
a.set_alert("")
a.set_alert_type("")
a.set_question_type("Fun_Fact")
a.set_option_type("option_text_field_snippet")
a.set_selection_type("single_selection")
a.set_progress(f"{int(a.question_id)/TOTAL_QUESTIONS :.2f}")
a.set_conditions("")
a.set_next_button_text("Next")

options = []
o = Options()
o.set_option_id("1")
of = TextField()
of.set_isMultiLine(True)
oft = TextItem()
oft.set_text("eg., “I'm the biggest Marvel fan”")
of.set_placeholder(oft)
oft = TextItem()
oft.set_text("Start typing...")
of.placeholderOnEditing(oft)
o.set_option_text_field(of)
options.append(o)

ops = options.__str__()
a.set_options(ops)
rep = a.__str__()