from Question import *
a = Question()
a.set_sort_key("4")
a.set_partition_key("questions")

a.set_question_id("4")
at = TextItem()
at.set_text("What's your marital status?")
a.set_title(at)
a.set_subtitle("")
a.set_subtitle_2("")
a.set_alert("")
a.set_alert_type("")
at = TextItem()
at.set_text("I certify that the above statement is true and that I am not in a committed relationship of any kind at the moment. I am aware that if untrue, IPC Section 415 and its consequences would apply")
a.set_consent_text(at)
a.set_question_type("question_marital_status")
a.set_layout("v_list")
a.set_selection_type("1")
a.set_progress(f"{int(a.question_id)/TOTAL_QUESTIONS :.2f}")
a.set_conditions("")
a.set_next_button_text("Next")
a.set_next_button_id(f"qs_{a.question_id}_next")

options = []
o = Option()
o.set_option_id("1")
ot = TextItem()
ot.set_text("Never Married")
o.set_option_title(ot)
o.set_option_type("option_card")
options.append(o)
o = Option()
o.set_option_id("2")
ot = TextItem()
ot.set_text("Widowed")
o.set_option_title(ot)
o.set_option_type("option_card")
bs = BottomSheet()
bs.set_id("children_bs")
bs.set_selection_type("1")
bs.set_button_2_text("Next")
bs.set_button_2_right_icon("e95c")
bs.set_button_2_id("children_bs_save")
ot = TextItem()
ot.set_text("Do you have children?")
bs.set_title(ot)
bs.set_screen_type("criteria_screen")
bs.set_layout("v_list")
bsops = []
bso = Option()
bso.set_option_id("2.1")
bsot = TextItem()
bsot.set_text("No")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bso = Option()
bso.set_option_id("2.2")
bsot = TextItem()
bsot.set_text("Yes")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bs.set_options(bsops)
o.set_bottom_sheet(bs)
options.append(o)

o = Option()
o.set_option_id("3")
ot = TextItem()
ot.set_text("Divorced")
o.set_option_title(ot)
o.set_option_type("option_card")
bs = BottomSheet()
bs.set_id("children_bs")
bs.set_selection_type("1")
bs.set_button_2_text("Next")
bs.set_button_2_left_icon("e95c")
bs.set_button_2_id("children_bs_save")
ot = TextItem()
ot.set_text("Do you have children?")
bs.set_title(ot)
bs.set_screen_type("criteria_screen")
bs.set_layout("v_list")
bsops = []
bso = Option()
bso.set_option_id("3.1")
bsot = TextItem()
bsot.set_text("No")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bso = Option()
bso.set_option_id("3.2")
bsot = TextItem()
bsot.set_text("Yes")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bs.set_options(bsops)
o.set_bottom_sheet(bs)
options.append(o)

o = Option()
o.set_option_id("4")
ot = TextItem()
ot.set_text("Separated/divorce in progress")
o.set_option_title(ot)
o.set_option_type("option_card")
bs = BottomSheet()
bs.set_id("children_bs")
bs.set_selection_type("1")
bs.set_button_2_text("Next")
bs.set_button_2_left_icon("e95c")
bs.set_button_2_id("children_bs_save")
ot = TextItem()
ot.set_text("Do you have children?")
bs.set_title(ot)
bs.set_screen_type("criteria_screen")
bs.set_layout("v_list")
bsops = []
bso = Option()
bso.set_option_id("4.1")
bsot = TextItem()
bsot.set_text("No")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bso = Option()
bso.set_option_id("4.2")
bsot = TextItem()
bsot.set_text("Yes")
bso.set_option_title(bsot)
bso.set_option_type("option_card")
bsops.append(bso)
bs.set_options(bsops)
o.set_bottom_sheet(bs)
options.append(o)

ops = options.__str__()
a.set_options(ops)
rep = a.__str__()