from Question import *
a = Question()
a.set_sort_key("4")
a.set_partition_key("questions")

a.set_question_id("4")
at = TextItem()
at.set_text("What's your marital status?")
a.set_title(at)
a.set_subtitle("")
a.set_subtitle_2("")
a.set_alert("")
a.set_alert_type("")

at = TextItem()
at.set_text("I certify that the above statement is true, and I am aware that if untrue, IPC Section 415 and its consequences would apply.")
a.set_consent_text(at)

a.set_question_type("Marital_Status")
a.set_layout("v_list")
a.set_selection_type("1")
a.set_progress(f"{int(a.question_id)/TOTAL_QUESTIONS :.2f}")
a.set_conditions("")
a.set_next_button_text("Next")

options = []
o = Option()
o.set_option_id("1")
ot = TextItem()
ot.set_text("Never Married")
o.set_option_title(ot)
o.set_option_type("option_card")
options.append(o)
o = Option()
o.set_option_id("2")
ot = TextItem()
ot.set_text("Windowed")
o.set_option_title(ot)
o.set_option_type("option_card")
options.append(o)
o = Option()
o.set_option_id("3")
ot = TextItem()
ot.set_text("Divorced")
o.set_option_title(ot)
o.set_option_type("option_card")
options.append(o)
o = Option()
o.set_option_id("4")
ot = TextItem()
ot.set_text("Separated/divorce in progress")
o.set_option_title(ot)
o.set_option_type("option_card")
options.append(o)

ops = options.__str__()
a.set_options(ops)
rep = a.__str__()