from Question import *
a = Question()
a.set_sort_key("80")
a.set_partition_key("questions")

a.set_question_id("80")
at = TextItem()
at.set_text("Will you be comfortable with a partner who has a disability or serious illness?")
a.set_title(at)
a.set_subtitle("")
a.set_subtitle_2("")
a.set_alert("Being open to different experiences may lead to meaningful connections and a faster match with someone who truly understands and appreciates you. You will know about the nature of their disability/illness when you see their profile and can accordingly decide to meet or not")
a.set_alert_type("info")
a.set_question_type("Partner_Disability")
a.set_option_type("list_cell_snippet")
a.set_selection_type("single_selection")
a.set_progress(f"{int(a.question_id)/TOTAL_QUESTIONS :.2f}")
a.set_conditions("")
a.set_next_button_text("Next")

options = []
o = Options()
o.set_option_id("1")
ot = TextItem()
ot.set_text("Yes")
o.set_option_title(ot)
options.append(o)
o = Options()
o.set_option_id("2")
ot = TextItem()
ot.set_text("No")
o.set_option_title(ot)
options.append(o)


ops = options.__str__()
a.set_options(ops)
rep = a.__str__()