from Question import *
a = Question()
a.set_sort_key("4")
a.set_partition_key("questions")

a.set_question_id("4")
at = TextItem()
at.set_text("How long do you think you want to date before getting married?")
a.set_title(at)

a.set_subtitle("")
a.set_subtitle_2("")
at = TextItem()
at.set_text("If you wish to date longer than 2 years, please select the “Exclusively Date” option in the previous step")
a.set_subtitle_3(at)

a.set_alert("")
a.set_alert_type("")
a.set_question_type("Date_To_Marry_Intent")
a.set_layout("option_card_v_list")
a.set_selection_type("1")
a.set_progress(f"{int(a.question_id)/TOTAL_QUESTIONS :.2f}")
# a.set_conditions("[{\"question_id\": \"5\", \"option\": \"2\"}]")
a.set_next_button_text("Next")
a.set_next_button_id(f"qs_{a.question_id}_next")

options = []
o = Option()
o.set_option_id("1")
ot = TextItem()
ot.set_text("3 months")
o.set_option_title(ot)
options.append(o)
o = Option()
o.set_option_id("2")
ot = TextItem()
ot.set_text("6 months")
o.set_option_title(ot)
options.append(o)
o = Option()
o.set_option_id("3")
ot = TextItem()
ot.set_text("1 year")
o.set_option_title(ot)
options.append(o)
o = Option()
o.set_option_id("4")
ot = TextItem()
ot.set_text("2 years")
o.set_option_title(ot)
options.append(o)

ops = options.__str__()
a.set_options(ops)

conditions = []
c = Conditions()
c.set_question_id("3")
c.set_option("2")
conditions.append(c)
conditions = conditions.__str__()
a.set_conditions(conditions)

rep = a.__str__()