from Question import *
a = Question()
a.set_sort_key("40")
a.set_partition_key("questions")

a.set_question_id("40")
at = TextItem()
at.set_text("Which gender(s) are you interested in meeting?")
a.set_title(at)
at = TextItem()
at.set_text("Select as many as you want")
a.set_subtitle(at)
a.set_subtitle_2("")
a.set_alert("")
a.set_alert_type("")

a.set_question_type("Partner_Gender_Preference")
a.set_layout("option_card_v_list")
a.set_selection_type("multi_selection")
a.set_progress(f"{int(a.question_id)/TOTAL_QUESTIONS :.2f}")
# a.set_conditions("[{\"question_id\": \"3\", \"option\": \"3\"}]")
a.set_next_button_text("Next")

options = []
o = Option()
o.set_option_id("1")
ot = TextItem()
ot.set_text("Trans-man")
o.set_option_title(ot)
options.append(o)
o = Option()
o.set_option_id("2")
options.append(o)
ot = TextItem()
ot.set_text("Trans-woman")
o.set_option_title(ot)
o = Option()
o.set_option_id("3")
ot = TextItem()
ot.set_text("Genderqueer")
o.set_option_title(ot)
options.append(o)
o = Option()
o.set_option_id("4")
ot = TextItem()
ot.set_text("Agender")
o.set_option_title(ot)
options.append(o)
o = Option()
o.set_option_id("5")
ot = TextItem()
ot.set_text("Genderless")
o.set_option_title(ot)
options.append(o)
o = Option()
o.set_option_id("6")
ot = TextItem()
ot.set_text("Non-binary")
o.set_option_title(ot)
options.append(o)
o = Option()
o.set_option_id("7")
ot = TextItem()
ot.set_text("Third gender")
o.set_option_title(ot)
options.append(o)
o = Option()
o.set_option_id("8")
ot = TextItem()
ot.set_text("Two-spirit")
o.set_option_title(ot)
options.append(o)

ops = options.__str__()
a.set_options(ops)

conditions = []
c = Conditions()
c.set_question_id("30")
c.set_option("3")
conditions.append(c)
conditions = conditions.__str__()
a.set_conditions(conditions)

rep = a.__str__()